// Code generated by internal/gendrivers from hurd.conf. DO NOT EDIT.
//
// Each blank import compiles a driver in: the package registers itself with
// github.com/mikefsq/goalpaca/registry in init(). Edit hurd.conf and run
// `make gen` to change the set.
//
// The fat tag selects the bundled build (`make fat`): without it (`make
// build`) this file is excluded, no driver is compiled in, and every device
// entry resolves to an installed driver binary.

//go:build fat

package main

import (
	_ "github.com/mikefsq/goalpaca-devices/asiair"
	_ "github.com/mikefsq/goalpaca-devices/asiam5"
	_ "github.com/mikefsq/goalpaca-devices/asieaf"
	_ "github.com/mikefsq/goalpaca-devices/asiefw"
	_ "github.com/mikefsq/goalpaca-devices/astrocam"
	_ "github.com/mikefsq/goalpaca-devices/focuscube"
	_ "github.com/mikefsq/goalpaca-devices/focuslynx"
	_ "github.com/mikefsq/goalpaca-devices/mgpbox"
	_ "github.com/mikefsq/goalpaca-devices/oasisfoc"
	_ "github.com/mikefsq/goalpaca-devices/oasisfw"
	_ "github.com/mikefsq/goalpaca-devices/onstep"
	_ "github.com/mikefsq/goalpaca-devices/ptpcam"
	_ "github.com/mikefsq/goalpaca-devices/rst"
	_ "github.com/mikefsq/goalpaca-devices/smpro"
	_ "github.com/mikefsq/goalpaca-devices/tenmicron"
	_ "github.com/mikefsq/goalpaca-devices/unihedron"
)
