// Code generated by internal/gendrivers from hurd.conf. DO NOT EDIT.
//
// Each blank import compiles a driver in: the package registers itself with
// github.com/mikefsq/goalpaca/registry in init(). Edit hurd.conf and run
// `make gen` to change the set.
package main

import (
	_ "github.com/mikefsq/goalpaca-devices/tenmicron"
	_ "github.com/mikefsq/goalpaca-devices/asiam5"
	_ "github.com/mikefsq/goalpaca-devices/onstep"
	_ "github.com/mikefsq/goalpaca-devices/rst"
	_ "github.com/mikefsq/goalpaca-devices/astrocam"
	_ "github.com/mikefsq/goalpaca-devices/asieaf"
	_ "github.com/mikefsq/goalpaca-devices/oasisfoc"
	_ "github.com/mikefsq/goalpaca-devices/focuscube"
	_ "github.com/mikefsq/goalpaca-devices/focuslynx"
	_ "github.com/mikefsq/goalpaca-devices/asiefw"
	_ "github.com/mikefsq/goalpaca-devices/oasisfw"
	_ "github.com/mikefsq/goalpaca-devices/mgpbox"
	_ "github.com/mikefsq/goalpaca-devices/unihedron"
	_ "github.com/mikefsq/goalpaca-devices/sim"
)
