// Command gendrivers turns hurd.conf (one driver package import path per line,
// # comments) into drivers_gen.go — the blank-import list that compiles those
// drivers into alpacahurd. Run via `make gen` (or `go run ./internal/gendrivers`)
// from the repo root.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("gendrivers: ")

	conf := "hurd.conf"
	if len(os.Args) > 1 {
		conf = os.Args[1]
	}
	f, err := os.Open(conf)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	var paths []string
	seen := map[string]bool{}
	sc := bufio.NewScanner(f)
	line := 0
	for sc.Scan() {
		line++
		s := strings.TrimSpace(sc.Text())
		if s == "" || strings.HasPrefix(s, "#") {
			continue
		}
		if i := strings.Index(s, "#"); i >= 0 { // trailing comment
			s = strings.TrimSpace(s[:i])
		}
		if strings.ContainsAny(s, " \t\"`") || strings.Contains(s, "@") {
			log.Fatalf("%s:%d: %q is not a bare package import path "+
				"(pin versions with `go get pkg@version`, not in hurd.conf)", conf, line, s)
		}
		if seen[s] {
			log.Fatalf("%s:%d: duplicate driver %s", conf, line, s)
		}
		seen[s] = true
		paths = append(paths, s)
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by internal/gendrivers from " + conf + ". DO NOT EDIT.\n")
	b.WriteString("//\n// Each blank import compiles a driver in: the package registers itself with\n")
	b.WriteString("// github.com/mikefsq/goalpaca/registry in init(). Edit hurd.conf and run\n")
	b.WriteString("// `make gen` to change the set.\n")
	b.WriteString("package main\n\nimport (\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t_ %q\n", p)
	}
	b.WriteString(")\n")

	if err := os.WriteFile("drivers_gen.go", []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("gendrivers: %d driver package(s) -> drivers_gen.go\n", len(paths))
}
